FROM node:20.20.1

WORKDIR /app
COPY . .

RUN rm -rf node_modules && npm ci && npm run build-np && npm run compress:brotli

WORKDIR /app/dist
RUN npm install --production
EXPOSE 3004

CMD [ "npm", "run", "serve:prod" ]
