sonar.projectKey=sphere-cb-orgPortal
sonar.projectName=sphere-cb-orgPortal
sonar.projectVersion=1.0
sonar.sources=src,project
sonar.exclusions=**/*.spec.ts,**/*.test.ts,**/node_modules/**,**/dist/**,**/coverage/**
sonar.sourceEncoding=UTF-8
sonar.typescript.tsconfigPath=tsconfig.json
sonar.typescript.exclusions=**/node_modules/**,**/dist/**
